(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,191,185);


(lib.folder = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#ECC85B","#E3AA3B"],[0,1],-37.9,-17.6,0,-37.9,-17.6,113.1).s().p("AoIHKQg8AAAAg8IAAsbQAAg8A8AAIEVAAQAxAFAVAzQAPAhAaAHIKNAAQA8AAAAA8IAAK7QAAA8g8AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.1,-45.8,116.2,91.6);


// stage content:
(lib.icon = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.folder("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(126.1,126.6,1.651,1.651,0,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(246));

	// Layer_4
	this.instance_1 = new lib.Bitmap1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-214,17);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},1).wait(246));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAcB2IgngBIgHAAIgkABIggABIAAgIIAcgGQAMgCADgGQACgGAAgOIAAhrQAAgLgEgFQgFgFgRgDIgOgEIABgIQAVgIAPgKQAOgLAMgXIAKAAIACAhIAAAlQAKgUAUgSQATgTAPAAQAOAAAIAIQAHAHAAAMQAAAKgGAGQgGAFgJAAQgJAAgLgEQgKgFgHAAQgGAAgGAGIgMAPIgIARIgDAOIAABcQAAAPAFAEQADAFAQACIAsAHIAAAIg");
	this.shape.setTransform(193.8,-89.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgoBrQgRgJgNgPQgNgQgHgVQgHgVAAgYQgBgYAJgVQAHgWAPgPQAPgQATgJQAUgJAXAAQARAAAPAFQAQAGALALQALALAHAQQAGAPABATIiaAAIgCAWQAAAVAFASQAHASALANQAMANAQAHQAQAHAVAAQATAAAQgHQAQgIATgSIADANQgpAxg8AAQgUAAgSgJgAgihXQgSAQgGAbIBVAAQARAAAJgDQAJgCgFgPQgFgPgLgMQgKgLgWAAQgaAAgRAPg");
	this.shape_1.setTransform(171.7,-88.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA2ClIgaALIgXAGIgTAFIgWABQglAAgaggQgbggAAgqQAAgaAIgXQAJgWAPgRQAPgRAUgKQAUgKAWAAQArAAAcAPIAAhhIgBgSQgCgHgFgEIgNgHIgXgHIAAgIIAjgFIAegJIAOAAIAAFLIACAQQABAFAEADIALADIAUABIAAAJIgnAIIgiAFgAgqgWQgNAHgKAOQgKANgGATQgGASAAAWQAAAWAHASQAGASALAMQALANAPAHQAPAGASAAQAQAAARgEQARgFAIgHIAAhqIgBgZQgCgOgGgKQgGgLgOgIQgOgHgYAAQgPAAgOAIg");
	this.shape_2.setTransform(145.4,-95.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAgC5IgggBIgfABIgeABIAAgJIAigHIALgEQACgDAAgIIAAkcQAAgMgGgFQgHgGgXgHIAAgHQAWgEAjgPIAMAAIAAFSQAAALADADQACADAIACIAeAFIAAAJg");
	this.shape_3.setTransform(123.3,-96.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgxBrQgVgIgQgQQgPgPgKgVQgJgWAAgZQAAgYAJgWQAKgVAQgPQAQgQAWgJQAWgIAaAAQAbAAAWAJQAVAJAQAQQAQAQAJAWQAJAVAAAXQAAAYgKAVQgJAVgQAQQgRAPgXAJQgXAJgaAAQgYAAgWgJgAg6hNQgWAcAAA2QAAAvAWAbQAWAaAjAAQARAAAPgHQAPgIALgNQALgOAGgTQAGgUAAgXQAAgXgFgTQgGgUgLgOQgKgOgPgIQgPgIgSAAQglAAgVAcg");
	this.shape_4.setTransform(101.4,-88.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdCvIgsgBIgoABIgeABIAAgIIAjgEQAKgBADgFQADgEAAgKIAAkZQAAgMgCgGQgDgGgJgBIghgEIAAgKIBBABICRAAIArAAIAegBIgBASIAAAXIAAAWIABASIgIAAIgLghIgJgUQgFgGgGgDIgPgCIh4AAQgJAAgDAGQgEAFAAANIAAB8IBzAAQALAAADgDQAEgDACgLIAJgoIAJAAIgBAZIAAAfIACBDIgIAAIgMgmQgDgLgGgDQgFgDgRABIhnAAIAACOQAAAPAFACIAQAEIAjAEIAAAIg");
	this.shape_5.setTransform(71.3,-95.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgoBrQgRgJgNgPQgNgQgHgVQgIgVABgYQAAgYAHgVQAJgWAOgPQAPgQATgJQAUgJAXAAQARAAAPAFQAPAGAMALQAMALAGAQQAGAPABATIiaAAIgDAWQABAVAFASQAHASALANQAMANAQAHQAQAHAUAAQAUAAAQgHQAQgIATgSIACANQgoAxg8AAQgUAAgSgJgAgihXQgSAQgGAbIBUAAQASAAAJgDQAJgCgFgPQgEgPgMgMQgKgLgWAAQgaAAgRAPg");
	this.shape_6.setTransform(160.7,-88.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAlCpIglAAIglAAIgYACIAAgJIAggGQARgEAAgQIAAhxQAAgNgHgHQgHgFgUgEIAAgIQAogKARgeIAKAAIAAC/QAAAJACADQADAFAHABIAdAHIAAAJgAgRiCQgGgGAAgKQAAgJAHgHQAHgIAJAAQAJAAAIAIQAIAHAAAJQAAAJgIAHQgIAHgJAAQgKAAgHgHg");
	this.shape_7.setTransform(125.8,-94.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhXCtQgUgJAAgNIADgIIAIgGQAEgBAIABQAHACAJAHQAeAYAXAAQARAAAQgJQAPgIAMgOQALgPAHgSQAHgSAAgUQAAgSgFgPQgEgPgJgLQgIgKgMgGQgLgGgOAAQgTAAgVASIgHgKIAMgKIANgKQA8guAAgfQAAgYgPgNQgPgOgXAAQgWAAgUAOQgUANgLAaIgKgFQAQgnAYgTQAWgSAhAAQAQAAANAFQAOAFAKAHQAKAIAGALQAGALAAAKQAAAWgOAUQgPATggAYQAVgBARAGQARAHAMANQALAMAGARQAGASAAAUQAAAbgLAYQgKAXgTASQgRARgaAKQgZAKgcAAQgnAAgUgJg");
	this.shape_8.setTransform(169.1,-95.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgWCyIgegBIhQACIAAgJIAfgFQAJgCACgEQADgEABgLIAAkLQAAgUgOgIQgNgHgegDIAAgLIAtAAIAcgBIBPgFIAJAAIAIAAQAgAAAWAIQAXAKAOAOQAOAOAHATQAGATAAASQAAAXgIASQgJATgOAPQgPAOgUAHQgUAJgXgBQgjABgSgWIAEgEQAOAFAPABQARAAAOgHQAQgEAKgLQALgKAGgPQAHgQAAgSQAAgQgGgPQgFgOgJgMQgLgMgPgIQgPgJgVgDIgZgBQgUAAgKAEIAAEtQAAAIADADQAEAEAMAEIAoAJIAAAIg");
	this.shape_9.setTransform(139.8,-95.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AiYibIAAEgQABAaAQACIA0AFIAAAJIhDgBIhOABIAAgJIAfgFIAQgEIAJgGIADgHIABgLIAAknIgygGIAAgJIAxACIA3gCIB8EVIBykVIA2ACQAbAAAXgCIAAAJIgiAHQgQAEgHAGQgGAHAAAQIAAD9QAAASADAGQADAGAKACIAwAJIAAAJIhVgBIgLAAIgdAAIgjABIAAgJIAhgGQANgDADgGQAEgFAAgRIAAkEIh8E1g");
	this.shape_10.setTransform(100.9,-95.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgEByIhUi+IgLgSQgEgDgJgCIgWgFIAAgJIA+ABIBBgBIAAAJIgjAFQgKACAAAHQgBAHALAYIA1B8IAzh+QAGgNgBgJQAAgPgWgDIgXgDIAAgJIA2ABIA8gBIAAAJIggAEQgJACgDAEIgKATIhPC9g");
	this.shape_11.setTransform(162.7,-87.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgKAJQgJAJgMAEQgNAGgSAAQgWgBgSgHQgRgJgMgOQgLgNgGgUQgFgSgBgXQAAgcAKgXQAKgXARgPQAQgPAUgHQAWgJAVABIASACIARAFIAQAGIAegPIAGACIAABXIAABWQAAAWAUAAIAHgCIAFgDIAGgEIAGADIgLARIgMAMQgJAFgLABQgRAAgIgMgAgphaQgNAGgMALQgKAKgIASQgHARAAAZQAAARAFASQAFAQAJANQAKAOANAHQAOAIARAAQAOAAAMgHQAMgHAIgNQAKgMAFgRQAGgSgBgSIAAgHQAAgogOgXQgPgWgiAAQgMAAgOAEg");
	this.shape_12.setTransform(135.8,-88.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AA8ByIgwhyIg6ByIgLAAIhjjHQgIgPgOgCIgNgCIAAgJIA1ACIA4gCIAAAJQgXAEgGAEQgGAFAGAMIBJCYIArhaIgVg6QgGgPgEgFQgFgEgEAAIgXgFIAAgJIA8ACIA8gCIAAAJIgcAFIgLAFIgGAGIAAAGIAEAHIA3CPIA5iFIADgLIgCgLIgHgJQgEgDgHgBIgWgEIAAgJIAvACQAiAAARgCIAAAJIgOADQgRAFgMAaIhQC4g");
	this.shape_13.setTransform(102.4,-87.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeBrQgVgJgPgQQgPgQgHgUQgIgVAAgXQAAgZAIgWQAHgWAQgPQAPgQAXgJQAXgIAcAAQAfAAATAJQAUAJAAAPQAAAHgFAGQgGAGgGABQgIABgGgHIgNgOIgSgOQgLgHgQAAQgQAAgNAJQgMAJgIAOQgIAOgEARQgDASAAATQAAASAGATQAGASAMAOQAMANARAIQAPAIAUAAQAXgBANgHQAMgHANgOIAHAOQgPATgWAIQgWAJgWAAQgZAAgVgJg");
	this.shape_14.setTransform(162.1,-88.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgKAJQgJAJgNAEQgNAGgRAAQgXgBgRgHQgRgJgMgOQgMgNgFgUQgFgSAAgXQgBgcAKgXQALgXAQgPQAQgPAUgHQAWgJAVABIASACIARAFIAQAGIAfgPIAEACIABBXIAABWQAAAWAUAAIAHgCIAFgDIAGgEIAFADIgKARIgMAMQgJAFgLABQgSAAgHgMgAgphaQgNAGgMALQgLAKgHASQgHARAAAZQAAARAFASQAFAQAJANQAKAOANAHQAOAIARAAQAOAAALgHQAMgHAKgNQAJgMAFgRQAFgSABgSIAAgHQgBgogOgXQgOgWgjAAQgNAAgNAEg");
	this.shape_15.setTransform(136.5,-88.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgVC4IgQAAIg9ACIAAgIIARgFIAOgDIAHgHIACgJIABgQIAAiKIgqgCIAAgJIAVgJIAMgIIAGgGIABgIQAAgOAEgWQAFgWALgWQALgXASgRQATgSAcgDIAIgBIAIgBQAuAAAAAYQABAIgGAGQgGAFgKAAIgKgDIgPgGIgQgFIgQgDQgSAAgJAIQgKAIgEANQgDAMgBARIAAAgIAAAaIAAAOIBIABIAAAUIhHACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_16.setTransform(98.9,-96.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgnBrQgTgJgMgPQgNgQgHgVQgIgVAAgYQABgYAHgVQAJgWAPgPQAOgQATgJQAUgJAWAAQATAAAOAFQAQAGALALQAMALAGAQQAHAPABATIicAAIgCAWQAAAVAHASQAGASAMANQALANAQAHQAQAHAUAAQAUAAAQgHQAQgIAUgSIABANQgoAxg8AAQgUAAgRgJgAgjhXQgRAQgGAbIBUAAQASAAAJgDQAIgCgEgPQgEgPgLgMQgLgLgWAAQgaAAgSAPg");
	this.shape_17.setTransform(158.7,-88.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgRCvIgUAAIgYAAIgkAAIgfACIAAgJIAXgFQAJgBACgEQADgDAAgLIAAj2QAAgVgIAAIgbgFIABgIQAdgLALgIQAMgIAIgNIAIAAIAAA3QAbgUAagIQAZgIAXABQAmADAYAeQAXAeAAAwQAAAZgIAWQgJAVgRARQgQARgWAJQgXAKgaAAQgeAAgjgRIAABWQAAAHAFAEQAEAEAOACIAiAGIAAAJgAABiBQgbAFgfAUIAAB5QAAAVASANQATANAcAAQASAAAQgHQAPgIALgMQAKgNAGgSQAHgRAAgUQAAgYgHgUQgGgTgMgNQgMgNgQgGQgLgEgNAAIgNABg");
	this.shape_18.setTransform(131.4,-84.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgJAJQgKAJgNAEQgNAGgQAAQgYgBgRgHQgRgJgMgOQgMgNgFgUQgGgSABgXQAAgcAKgXQAKgXAQgPQAQgPAVgHQAUgJAWABIASACIARAFIAQAGIAfgPIAEACIABBXIAABWQAAAWATAAIAIgCIAGgDIAFgEIAFADIgKARIgMAMQgIAFgMABQgRAAgIgMgAgphaQgNAGgMALQgLAKgHASQgHARAAAZQAAARAFASQAFAQAJANQAJAOAOAHQANAIASAAQAOAAALgHQAMgHAKgNQAJgMAFgRQAFgSABgSIAAgHQAAgogPgXQgOgWgjAAQgNAAgNAEg");
	this.shape_19.setTransform(103.4,-88.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgJAJQgKAJgNAEQgNAGgRAAQgXgBgRgHQgRgJgMgOQgMgNgFgUQgGgSABgXQgBgcALgXQAKgXAQgPQAQgPAVgHQAVgJAVABIASACIARAFIAQAGIAfgPIAEACIABBXIAABWQAAAWAUAAIAHgCIAFgDIAGgEIAFADIgKARIgMAMQgJAFgLABQgSAAgHgMgAgphaQgNAGgMALQgLAKgHASQgHARAAAZQAAARAFASQAFAQAJANQAKAOANAHQAOAIARAAQAOAAALgHQAMgHAKgNQAJgMAFgRQAFgSABgSIAAgHQAAgogPgXQgOgWgjAAQgNAAgNAEg");
	this.shape_20.setTransform(140.4,-88.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AA3BmQgHgMAAgVIAAgRIgLAXQgGALgJAJQgKAJgNAEQgNAGgQAAQgYgBgRgHQgSgJgLgOQgLgNgGgUQgGgSAAgXQAAgcALgXQAJgXARgPQAQgPAVgHQAUgJAWABIASACIARAFIAQAGIAegPIAFACIABBXIAABWQAAAWATAAIAIgCIAGgDIAFgEIAGADIgLARIgNAMQgHAFgMABQgSAAgIgMgAgphaQgNAGgLALQgLAKgIASQgHARAAAZQAAARAFASQAEAQAKANQAJAOAOAHQANAIASAAQAOAAAMgHQAMgHAIgNQAKgMAFgRQAGgSAAgSIAAgHQAAgogPgXQgOgWgjAAQgNAAgNAEg");
	this.shape_21.setTransform(96.9,-88.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgEByIhUi+IgLgSQgEgDgJgCIgXgFIAAgJIA/ABIBBgBIAAAJIgjAFQgLACABAHQAAAHAKAYIA1B8IAzh+QAFgNABgJQAAgPgYgDIgVgDIAAgJIA1ABIA8gBIAAAJIggAEQgJACgDAEIgKATIhPC9g");
	this.shape_22.setTransform(148.5,-87.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AA7ByIgvhyIg6ByIgMAAIhjjHQgHgPgNgCIgOgCIAAgJIA0ACIA5gCIAAAJQgWAEgHAEQgGAFAFAMIBJCYIAshaIgVg6QgGgPgEgFQgEgEgFAAIgXgFIAAgJIA8ACIA8gCIAAAJIgcAFIgMAFIgFAGIAAAGIAEAHIA3CPIA4iFIAFgLIgDgLIgHgJQgEgDgHgBIgWgEIAAgJIAuACQAjAAARgCIAAAJIgPADQgRAFgLAaIhRC4g");
	this.shape_23.setTransform(116.6,-87.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AA3BmQgHgMAAgVIAAgRIgLAXQgGALgKAJQgJAJgMAEQgNAGgRAAQgYgBgRgHQgSgJgLgOQgMgNgFgUQgGgSAAgXQABgcAJgXQALgXAQgPQAQgPAUgHQAVgJAWABIASACIARAFIAQAGIAegPIAGACIAABXIAABWQAAAWATAAIAIgCIAGgDIAFgEIAGADIgLARIgNAMQgIAFgLABQgSAAgIgMgAgphaQgNAGgLALQgLAKgIASQgHARAAAZQAAARAFASQAFAQAJANQAKAOANAHQANAIASAAQAOAAAMgHQAMgHAIgNQAKgMAFgRQAGgSgBgSIAAgHQAAgogOgXQgPgWgiAAQgMAAgOAEg");
	this.shape_24.setTransform(132.8,-88.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgJAJQgKAJgNAEQgNAGgRAAQgXgBgRgHQgRgJgMgOQgMgNgFgUQgFgSAAgXQgBgcALgXQAKgXAQgPQAQgPAUgHQAWgJAVABIASACIARAFIAQAGIAfgPIAEACIABBXIAABWQAAAWAUAAIAHgCIAFgDIAGgEIAFADIgKARIgMAMQgJAFgLABQgSAAgHgMgAgphaQgNAGgMALQgLAKgHASQgHARAAAZQAAARAFASQAFAQAJANQAKAOANAHQAOAIARAAQAOAAALgHQAMgHAKgNQAJgMAFgRQAFgSAAgSIAAgHQAAgogOgXQgOgWgjAAQgNAAgNAEg");
	this.shape_25.setTransform(104.5,-88.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("Ag3CYQgSgEgJgIQgKgGgCgIIgDgNQAAgKAGgDQAEgGAJAAQANABADAHIAHAQQAEAIALAIQAJAHAbAAQAkAAATgUQATgTAAgmIAAhDIgLAZQgHANgKAJQgLALgOAFQgNAHgQAAQgUgBgQgHQgRgHgNgNQgLgOgIgSQgGgSAAgVQgBgaAJgVQAJgVAPgRQAPgPAUgJQAUgIAVAAIAcACIATAFIAQAGIAfgUIAGABIAADUQAAAVgJASQgIATgPANQgPANgUAIQgVAIgXAAQgfAAgSgFgAgaiBQgMAHgJAKQgJAMgHARQgFARAAAWQAAARAEAQQADAQAHANQAJAMALAJQANAHASAAQAPAAAOgIQANgIAKgOQAJgNAGgQQAFgQABgRIAAgFQAAgSgDgPQgDgOgJgMQgHgMgOgGQgNgHgVAAQgNABgNAFg");
	this.shape_26.setTransform(156.8,-84.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("Ag3CYQgSgEgKgIQgJgGgDgIIgCgNQAAgKAFgDQAGgGAIAAQANABAEAHIAGAQQAFAIAJAIQAKAHAaAAQAlAAATgUQATgTAAgmIAAhDIgLAZQgHANgLAJQgKALgNAFQgOAHgQAAQgUgBgQgHQgRgHgMgNQgNgOgGgSQgIgSAAgVQABgaAIgVQAJgVAPgRQAPgPAUgJQATgIAWAAIAbACIAUAFIAQAGIAfgUIAFABIAADUQAAAVgIASQgIATgPANQgOANgVAIQgUAIgYAAQgfAAgSgFgAgZiBQgNAHgJAKQgKAMgFARQgGARAAAWQAAARADAQQAEAQAIANQAHAMANAJQALAHATAAQAPAAANgIQANgIAKgOQALgNAFgQQAGgQAAgRIAAgFQAAgSgDgPQgEgOgHgMQgJgMgNgGQgNgHgVAAQgNABgMAFg");
	this.shape_27.setTransform(130.2,-84.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("Ag3CYQgSgEgKgIQgJgGgDgIIgCgNQAAgKAFgDQAGgGAIAAQANABAEAHIAHAQQADAIAKAIQAKAHAaAAQAlAAATgUQATgTAAgmIAAhDIgLAZQgHANgLAJQgJALgOAFQgOAHgQAAQgUgBgQgHQgRgHgNgNQgMgOgGgSQgIgSAAgVQAAgaAJgVQAIgVAQgRQAPgPAUgJQAUgIAVAAIAbACIAUAFIAQAGIAfgUIAFABIAADUQABAVgJASQgIATgPANQgOANgVAIQgUAIgYAAQgfAAgSgFgAgZiBQgNAHgJAKQgKAMgFARQgGARAAAWQAAARADAQQAEAQAIANQAHAMANAJQALAHATAAQAPAAAOgIQAMgIAKgOQALgNAFgQQAGgQAAgRIAAgFQAAgSgDgPQgEgOgHgMQgJgMgMgGQgOgHgVAAQgNABgMAFg");
	this.shape_28.setTransform(178,-84.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("ACUB0QgdAAgWABIAAgJIAQgDQANgDAGgEQAGgEAAgNIAAhjQAAghgNgPQgNgPgdAAQglAAgbAgIAAB+IACASQACAGALACIAcAGIAAAJIg8gCIg+ACIAAgJIAQgEQAQgEAHgFQAHgEAAgMIAAhjQAAgcgOgRQgNgRgYAAQgJAAgMAFIgXAKIgSAOQgHAIAAAIIAAByQAAANAEAFQADAFAIACIAdAGIAAAJQg5gEg6AEIAAgJIAQgDQAMgDAFgFQAEgFAAgMIAAh4IgBgLIgFgIIgJgFIgPgEIAAgIQAdgIAYgiIALAAIAAA2QAYgWAUgLQATgLAYAAIAVACIAQAGIAOANIANAUQATgTAUgLQAUgLAdAAQAeAAATAUQASAUAAAlIAABwQAAAVAJABIAZAFIAAAJQgdgCgdAAg");
	this.shape_29.setTransform(89.7,-89.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgEByIhVi+IgKgSQgEgDgIgCIgYgFIAAgJIA/ABIBBgBIAAAJIgjAFQgLACAAAHQAAAHAKAYIA1B8IA0h+QAGgNAAgJQAAgPgYgDIgVgDIAAgJIA2ABIA6gBIAAAJIgeAEQgKACgEAEIgKATIhOC9g");
	this.shape_30.setTransform(136.4,-87.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgEByIhVi+IgKgSQgEgDgIgCIgXgFIAAgJIA+ABIBBgBIAAAJIgjAFQgLACAAAHQAAAHAKAYIA1B8IA0h+QAGgNAAgJQAAgPgXgDIgWgDIAAgJIA2ABIA6gBIAAAJIgeAEQgKACgEAEIgKATIhOC9g");
	this.shape_31.setTransform(166.1,-87.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AhEBmIgFhAIAJAAQAEAQAHAMQAHAMAKAIQAIAJALAEQAKAFAJAAQAUAAANgLQAMgLAAgSQAAggg0gTQglgNgQgQQgPgPAAgZQgBgbAWgQQAWgQAfAAQAjAAAWANIAEAxIgLAAQgCgJgGgJIgOgQIgQgLQgIgEgGAAQgpAAAAAlQAAAPAOAKQANALAaAKQBAAYgBArQAAAQgFANQgHAMgKAJQgKAJgPAEQgPAFgOAAQgoAAgagOg");
	this.shape_32.setTransform(134.1,-88.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgJAJQgKAJgNAEQgNAGgQAAQgYgBgRgHQgRgJgMgOQgMgNgFgUQgGgSABgXQgBgcALgXQAKgXAQgPQAQgPAVgHQAVgJAVABIASACIARAFIAQAGIAfgPIAEACIABBXIAABWQAAAWAUAAIAHgCIAFgDIAGgEIAFADIgKARIgMAMQgJAFgLABQgSAAgHgMgAgphaQgNAGgMALQgLAKgHASQgHARAAAZQAAARAFASQAFAQAJANQAKAOANAHQAOAIARAAQAOAAALgHQAMgHAKgNQAJgMAFgRQAFgSABgSIAAgHQAAgogPgXQgOgWgjAAQgNAAgNAEg");
	this.shape_33.setTransform(109.8,-88.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgEByIhUi+IgLgSQgEgDgJgCIgWgFIAAgJIA+ABIBBgBIAAAJIgjAFQgLACAAAHQAAAHAKAYIA1B8IA0h+QAGgNgBgJQABgPgXgDIgXgDIAAgJIA2ABIA8gBIAAAJIgfAEQgKACgEAEIgKATIhOC9g");
	this.shape_34.setTransform(170.5,-87.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AA8ByIgxhyIg5ByIgLAAIhjjHQgIgPgOgCIgMgCIAAgJIA0ACIA5gCIAAAJQgXAEgHAEQgGAFAGAMIBJCYIArhaIgVg6QgGgPgEgFQgFgEgEAAIgYgFIAAgJIA9ACIA8gCIAAAJIgbAFIgMAFIgGAGIAAAGIADAHIA3CPIA6iFIADgLIgCgLIgHgJQgFgDgGgBIgXgEIAAgJIAwACQAiAAAQgCIAAAJIgNADQgRAFgMAaIhQC4g");
	this.shape_35.setTransform(94.6,-87.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgEByIhUi+IgLgSQgEgDgJgCIgWgFIAAgJIA+ABIBBgBIAAAJIgjAFQgKACAAAHQAAAHAKAYIA1B8IAzh+QAFgNAAgJQAAgPgWgDIgXgDIAAgJIA2ABIA8gBIAAAJIggAEQgJACgDAEIgKATIhPC9g");
	this.shape_36.setTransform(151.3,-87.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgKAJQgJAJgMAEQgOAGgRAAQgWgBgSgHQgRgJgMgOQgLgNgGgUQgFgSgBgXQAAgcAKgXQAKgXARgPQAQgPAUgHQAWgJAVABIASACIARAFIAQAGIAegPIAGACIAABXIAABWQAAAWAUAAIAHgCIAFgDIAGgEIAFADIgKARIgMAMQgJAFgLABQgSAAgHgMgAgphaQgNAGgMALQgKAKgIASQgHARAAAZQAAARAFASQAEAQAKANQAKAOANAHQAOAIARAAQAOAAAMgHQALgHAKgNQAJgMAFgRQAFgSAAgSIAAgHQAAgogOgXQgOgWgjAAQgMAAgOAEg");
	this.shape_37.setTransform(124.4,-88.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AATB2IAAgJIAegFQAMgBAAgVIAAheQAAgfgKgSQgLgUgeAAQgjAAgiAiIAACIQAAAIANAEIAhAIIAAAJIgSgBIgYgBIgTAAIg8ACIAAgJIAegGQALgCAAgPIAAhuQAAgRgHgGQgIgGgRgDIAAgLQAjgHAWgqIAJAAIAAAxQAUgRAagMQAZgLAUABQBAAAAABMIAABvQABAKACAFQADAHAIABIAZAFIAAAJQg6gEg6AEg");
	this.shape_38.setTransform(95,-89.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("Ag3CYQgSgEgKgIQgJgGgDgIIgCgNQAAgKAFgDQAGgGAIAAQANABAEAHIAHAQQADAIAKAIQAKAHAaAAQAlAAATgUQATgTAAgmIAAhDIgLAZQgHANgLAJQgJALgOAFQgOAHgQAAQgUgBgQgHQgRgHgNgNQgMgOgGgSQgIgSAAgVQAAgaAJgVQAIgVAQgRQAPgPAUgJQAUgIAVAAIAbACIAUAFIAQAGIAfgUIAFABIAADUQABAVgJASQgIATgPANQgOANgVAIQgUAIgYAAQgfAAgSgFgAgZiBQgNAHgJAKQgKAMgFARQgGARAAAWQAAARADAQQAEAQAIANQAHAMANAJQALAHATAAQAPAAAOgIQANgIAJgOQALgNAFgQQAGgQAAgRIAAgFQAAgSgDgPQgEgOgHgMQgJgMgMgGQgOgHgVAAQgNABgMAFg");
	this.shape_39.setTransform(127.6,-84.6);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AhXCtQgUgJAAgNIADgIIAIgGQAEgBAIABQAHACAJAHQAeAYAXAAQARAAAQgJQAPgIAMgOQALgPAHgSQAHgSAAgUQAAgSgFgPQgEgPgJgLQgIgKgMgGQgLgGgOAAQgTAAgVASIgHgKIAMgKIANgKQA8guAAgfQAAgYgPgNQgPgOgXAAQgWAAgUAOQgUANgLAaIgKgFQAQgnAYgTQAWgSAhAAQAQAAANAFQAOAFAKAHQAKAIAGALQAGALAAAKQAAAWgOAUQgPATggAYQAVgBARAGQARAHAMANQALAMAGARQAGASAAAUQAAAbgLAYQgKAXgSASQgSARgaAKQgZAKgcAAQgnAAgUgJg");
	this.shape_40.setTransform(102.1,-95.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAcB2IgngBIgHAAIgkABIggABIAAgIIAcgGQAMgCADgGQACgGAAgOIAAhrQAAgLgEgFQgFgFgRgDIgOgEIABgIQAWgIAOgKQAPgLALgXIAKAAIABAhIABAlQALgUATgSQAUgTAOAAQAOAAAIAIQAHAHAAAMQAAAKgGAGQgGAFgJAAQgJAAgLgEQgKgFgHAAQgGAAgGAGIgMAPIgHARIgEAOIAABcQAAAPAFAEQADAFAQACIAsAHIAAAIg");
	this.shape_41.setTransform(115.6,-89.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AA3BmQgHgMAAgVIAAgRIgLAXQgGALgKAJQgJAJgMAEQgNAGgSAAQgWgBgSgHQgSgJgLgOQgLgNgGgUQgFgSgBgXQABgcAJgXQALgXAQgPQAQgPAUgHQAWgJAVABIASACIARAFIAQAGIAegPIAGACIAABXIAABWQAAAWATAAIAIgCIAFgDIAGgEIAGADIgLARIgNAMQgHAFgMABQgRAAgJgMgAgphaQgNAGgLALQgLAKgIASQgHARAAAZQAAARAFASQAFAQAJANQAKAOANAHQAOAIARAAQAOAAAMgHQALgHAJgNQAKgMAFgRQAGgSgBgSIAAgHQAAgogOgXQgPgWgiAAQgMAAgOAEg");
	this.shape_42.setTransform(118.3,-88.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAcB2IgngBIgHAAIglABIgfABIAAgIIAcgGQALgCAEgGQADgGAAgOIAAhrQAAgLgGgFQgEgFgRgDIgPgEIABgIQAXgIAOgKQAOgLAMgXIAKAAIACAhIAAAlQAKgUAUgSQATgTAPAAQAOAAAHAIQAIAHAAAMQAAAKgGAGQgGAFgJAAQgJAAgKgEQgKgFgIAAQgGAAgHAGIgLAPIgIARIgDAOIAABcQAAAPAEAEQAFAFAPACIArAHIAAAIg");
	this.shape_43.setTransform(93.6,-89.5);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("ABkC5IgjgBIgjABIgZABIAAgIIAZgDQAMgBABgEIgEgIIgHgLIgOgSIgUgaIgQgTIgJgLIgHgGIgEgBIgEAAIgDAAIgKAAIAABQQgBAOADAEQADAEAIABIAWAFIAAAIIgWgBIgfgBIgfABIgVABIAAgIIAUgEQALgCACgDQADgFAAgOIAAkVIgBgLIgFgGIgLgEIgSgEIAAgIQAcgFAggUIAJAAIAAD2QALABALgIIAegVIAZgYQAIgHAAgEQAAgMgjgFIAAgJIBxAAIAAAJQgoAEgeAYIgvArIAZAhIAeAnIAfAhQAOAOALABIAGACIAHABIALADIAAAIg");
	this.shape_44.setTransform(139.6,-96.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgEByIhUi+IgLgSQgEgDgJgCIgXgFIAAgJIA/ABIBBgBIAAAJIgjAFQgLACABAHQAAAHAKAYIA1B8IAzh+QAFgNAAgJQAAgPgXgDIgWgDIAAgJIA2ABIA8gBIAAAJIggAEQgJACgDAEIgKATIhPC9g");
	this.shape_45.setTransform(147.6,-87.7);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgWC4IgPAAIg9ACIAAgIIASgFIAMgDIAHgHIADgJIAAgQIAAiKIgogCIAAgJIATgJIANgIIAGgGIABgIQAAgOAFgWQAEgWALgWQALgXATgRQARgSAdgDIAIgBIAIgBQAvAAAAAYQgBAIgFAGQgGAFgJAAIgLgDIgOgGIgRgFIgRgDQgRAAgJAIQgJAIgEANQgFAMAAARIAAAgIAAAaIAAAOIBHABIAAAUIhGACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_46.setTransform(111.5,-96.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AAXC2IAAhqIiOAAIAAgTIBDhgIAyhHIAxhHIAOAAIAADnIA7AAIAAAaIg7AAIAABqgAhcAyIBzAAIAAirQhKBpgpBCg");
	this.shape_47.setTransform(127.2,-95.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgVC4IgQAAIg9ACIAAgIIARgFIAOgDIAGgHIADgJIABgQIAAiKIgqgCIAAgJIAUgJIANgIIAGgGIABgIQAAgOAEgWQAFgWALgWQALgXASgRQASgSAdgDIAIgBIAIgBQAuAAAAAYQABAIgGAGQgGAFgJAAIgKgDIgQgGIgQgFIgRgDQgRAAgJAIQgKAIgDANQgEAMgBARIgBAgIAAAaIABAOIBHABIAAAUIhGACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_48.setTransform(105.9,-96.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AhZC/IAAkdIABgZQABgKgDgIQgDgIgIgGQgIgGgSgHIACgIIBHgSIAACmQAugTAiAAQAXAAASAIQAUAJANAPQANAOAIAVQAHAVAAAXQAAAbgJAWQgJAWgQAQQgPAQgVAIQgWAJgYAAIgWgDIgYgHIgRgHIgIgDQgJAAgMAXgAglgSQgRAHAAAIIAAB6QAAAZAQAOQAPAOAZAAQBVAAAAhdQAAgWgGgUQgGgTgMgOQgLgNgQgIQgQgIgSAAQgXAAgQAHg");
	this.shape_49.setTransform(174.6,-95.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgEByIhVi+IgKgSQgEgDgIgCIgYgFIAAgJIA/ABIBBgBIAAAJIgjAFQgLACAAAHQABAHAJAYIA1B8IA0h+QAGgNAAgJQAAgPgYgDIgVgDIAAgJIA2ABIA6gBIAAAJIgeAEQgKACgEAEIgKATIhOC9g");
	this.shape_50.setTransform(147.3,-87.7);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AAcB2IgngBIgHAAIglABIgfABIAAgIIAcgGQALgCADgGQAEgGAAgOIAAhrQAAgLgGgFQgEgFgQgDIgQgEIABgIQAXgIAOgKQAOgLAMgXIAKAAIACAhIAAAlQAKgUAUgSQATgTAPAAQAOAAAHAIQAIAHAAAMQAAAKgGAGQgGAFgJAAQgJAAgKgEQgKgFgIAAQgGAAgHAGIgLAPIgHARIgEAOIAABcQAAAPAEAEQAEAFAQACIArAHIAAAIg");
	this.shape_51.setTransform(80,-89.5);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AA7ByIgvhyIg6ByIgLAAIhkjHQgHgPgNgCIgOgCIAAgJIA0ACIA5gCIAAAJQgWAEgHAEQgGAFAFAMIBJCYIAshaIgVg6QgGgPgEgFQgFgEgEAAIgXgFIAAgJIA8ACIA8gCIAAAJIgcAFIgLAFIgGAGIAAAGIAEAHIA3CPIA4iFIAFgLIgDgLIgHgJQgEgDgHgBIgWgEIAAgJIAuACQAjAAARgCIAAAJIgPADQgRAFgLAaIhRC4g");
	this.shape_52.setTransform(81,-87.9);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AhZC/IAAkdIABgZQABgKgDgIQgDgIgIgGQgIgGgSgHIABgIIBIgSIAACmQAugTAhAAQAYAAATAIQASAJAOAPQAOAOAHAVQAHAVAAAXQAAAbgJAWQgJAWgPAQQgQAQgVAIQgWAJgXAAIgYgDIgXgHIgRgHIgIgDQgKAAgMAXgAglgSQgRAHAAAIIAAB6QAAAZAQAOQAPAOAaAAQBUAAAAhdQAAgWgGgUQgGgTgMgOQgLgNgQgIQgQgIgSAAQgXAAgQAHg");
	this.shape_53.setTransform(115,-95.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AA2ClIgaALIgXAGIgTAFIgWABQglAAgaggQgbggAAgqQAAgaAIgXQAJgWAPgRQAPgRAUgKQAUgKAWAAQArAAAcAPIAAhhIgBgSQgCgHgFgEIgNgHIgXgHIAAgIIAjgFIAegJIAOAAIAAFLIACAQQABAFAEADIALADIAUABIAAAJIgnAIIgiAFgAgqgWQgNAHgKAOQgKANgGATQgGASAAAWQAAAWAHASQAGASALAMQALANAPAHQAPAGASAAQAQAAARgEQARgFAIgHIAAhqIgBgZQgCgOgGgKQgGgLgOgIQgOgHgYAAQgPAAgOAIg");
	this.shape_54.setTransform(102.5,-95.7);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAYC2IAAhqIiPAAIAAgTIBDhgIAyhHIAxhHIAOAAIAADnIA7AAIAAAaIg7AAIAABqgAhcAyIB0AAIAAirQhLBpgpBCg");
	this.shape_55.setTransform(166.9,-95.1);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AhZC/IAAkdIABgZQABgKgDgIQgDgIgIgGQgIgGgSgHIABgIIBIgSIAACmQAugTAhAAQAYAAASAIQATAJAOAPQAOAOAHAVQAHAVAAAXQAAAbgJAWQgJAWgPAQQgQAQgVAIQgVAJgYAAIgYgDIgWgHIgSgHIgIgDQgJAAgNAXgAgmgSQgQAHAAAIIAAB6QAAAZAPAOQAPAOAbAAQBUAAAAhdQAAgWgGgUQgGgTgLgOQgMgNgQgIQgPgIgTAAQgXAAgRAHg");
	this.shape_56.setTransform(145.4,-95.7);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgoBrQgSgJgMgPQgNgQgHgVQgHgVAAgYQgBgYAJgVQAHgWAPgPQAPgQATgJQAUgJAXAAQARAAAQAFQAPAGALALQAMALAGAQQAGAPABATIibAAIgBAWQAAAVAFASQAHASALANQAMANARAHQAPAHAVAAQASAAARgHQAQgIAUgSIACANQgoAxg9AAQgUAAgSgJgAgihXQgSAQgGAbIBVAAQARAAAJgDQAJgCgFgPQgFgPgLgMQgKgLgWAAQgaAAgRAPg");
	this.shape_57.setTransform(119.1,-88.5);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AA8ByIgxhyIg5ByIgLAAIhjjHQgIgPgOgCIgMgCIAAgJIA0ACIA5gCIAAAJQgXAEgHAEQgGAFAGAMIBJCYIArhaIgVg6QgGgPgEgFQgFgEgEAAIgYgFIAAgJIA9ACIA8gCIAAAJIgbAFIgMAFIgFAGIAAAGIACAHIA3CPIA6iFIADgLIgCgLIgHgJQgFgDgFgBIgYgEIAAgJIAwACQAiAAAQgCIAAAJIgNADQgRAFgMAaIhQC4g");
	this.shape_58.setTransform(88.3,-87.9);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AhZC/IAAkdIABgZQABgKgDgIQgDgIgIgGQgIgGgSgHIABgIIBIgSIAACmQAugTAhAAQAYAAATAIQASAJAOAPQAOAOAHAVQAHAVAAAXQAAAbgJAWQgJAWgPAQQgQAQgVAIQgVAJgYAAIgYgDIgWgHIgSgHIgIgDQgJAAgNAXgAgmgSQgQAHAAAIIAAB6QAAAZAQAOQAPAOAaAAQBUAAAAhdQAAgWgGgUQgGgTgMgOQgLgNgQgIQgQgIgSAAQgXAAgRAHg");
	this.shape_59.setTransform(92.6,-95.7);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("ABgBrIgdgBIgeABIgXABIAAgIIATgFQAOgEAAgGQAAgGgIgKIgFgGIgDgEIgkgvIgqA5QgGAHAAAGQAAALAWADIARAEIAAAIIgygCIg2ACIAAgIIAQgEQAOgDALgJQALgJAMgRIApg3Ig3hDQgZgdgJgBIgSgFIAAgJIA2ACIA4gCIAAAKIgUAEQgJABAAAHQAAAHANAPIAgApIAfgqQAIgJgBgIQAAgMgPgCIgRgDIAAgJIAbACIAdAAQAhAAAMgCIAAAJIgTAEQgNACgKAIQgKAGgMARIgkAwIBDBVQAQAUAJADIAQAGIAAAIg");
	this.shape_60.setTransform(156.1,-88.4);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgPCJQgJgEgGgIQgFgIgBgOIgCgiIAAh+IgPAAIgPABQgIAAAAgEQAAgFAHgDQAZgKAKgNIAMgTIAMgdIAHAAIAAAeIAAAfIBMgCIAAAUIhMACIAAByQAAAhAEARQAFARAWgBQARgBAbgPIAFAIQgMAOgPAFQgPAHgdgBQgMAAgJgCg");
	this.shape_61.setTransform(112.7,-90.8);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgWC4IgPAAIg9ACIAAgIIARgFIAOgDIAHgHIACgJIAAgQIAAiKIgpgCIAAgJIAVgJIAMgIIAGgGIABgIQAAgOAEgWQAFgWALgWQALgXASgRQATgSAcgDIAIgBIAIgBQAuAAABAYQAAAIgGAGQgGAFgKAAIgKgDIgPgGIgQgFIgQgDQgSAAgJAIQgJAIgFANQgEAMAAARIAAAgIAAAaIAAAOIBIABIAAAUIhHACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_62.setTransform(153,-96.2);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("Ag3CYQgSgEgKgIQgJgGgCgIIgDgNQAAgKAGgDQAEgGAJAAQANABADAHIAHAQQAEAIALAIQAJAHAbAAQAkAAATgUQATgTAAgmIAAhDIgLAZQgHANgKAJQgLALgOAFQgNAHgQAAQgTgBgRgHQgRgHgMgNQgMgOgIgSQgGgSAAgVQgBgaAJgVQAJgVAPgRQAPgPAUgJQAUgIAVAAIAcACIATAFIAQAGIAfgUIAGABIAADUQAAAVgJASQgIATgPANQgOANgVAIQgVAIgXAAQgfAAgSgFgAgaiBQgMAHgJAKQgJAMgHARQgFARAAAWQAAARADAQQAEAQAHANQAJAMALAJQAMAHATAAQAPAAANgIQANgIALgOQAJgNAGgQQAFgQABgRIAAgFQAAgSgDgPQgDgOgJgMQgHgMgOgGQgNgHgVAAQgNABgNAFg");
	this.shape_63.setTransform(111.4,-84.6);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("Ag3CYQgSgEgKgIQgJgGgCgIIgDgNQAAgKAFgDQAGgGAIAAQANABAEAHIAGAQQAFAIAJAIQAKAHAbAAQAkAAATgUQATgTAAgmIAAhDIgLAZQgHANgLAJQgKALgNAFQgOAHgQAAQgUgBgQgHQgRgHgMgNQgNgOgGgSQgIgSAAgVQABgaAIgVQAJgVAPgRQAPgPAUgJQATgIAWAAIAbACIAUAFIAQAGIAfgUIAFABIAADUQAAAVgIASQgIATgPANQgOANgVAIQgUAIgYAAQgfAAgSgFgAgZiBQgNAHgJAKQgKAMgFARQgGARAAAWQAAARADAQQAEAQAIANQAHAMANAJQALAHATAAQAPAAANgIQANgIAKgOQALgNAFgQQAGgQAAgRIAAgFQAAgSgDgPQgEgOgHgMQgJgMgNgGQgNgHgVAAQgNABgMAFg");
	this.shape_64.setTransform(162.1,-84.6);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AgoBrQgRgJgNgPQgNgQgHgVQgIgVABgYQAAgYAIgVQAHgWAPgPQAPgQATgJQAUgJAXAAQARAAAPAFQAPAGAMALQALALAHAQQAGAPABATIiaAAIgCAWQAAAVAFASQAHASALANQAMANAQAHQAQAHAUAAQAUAAAQgHQAQgIATgSIADANQgpAxg8AAQgUAAgSgJgAgihXQgSAQgGAbIBVAAQARAAAJgDQAJgCgFgPQgEgPgMgMQgKgLgWAAQgaAAgRAPg");
	this.shape_65.setTransform(137.4,-88.5);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgjDpQAVgTAJgZQAIgaABgnIAAiUIAAgYQAAgKgCgFQgCgFgIgCIgXgEIAAgLQAqgMASgbIAIAAIAAD0QAAAigSAgQgRAggiAVgAgGjFQgFgIgBgKQABgJAGgHQAFgIAMABQAWAAAAAYQAAALgGAHQgIAGgKAAIgDAAQgIAAgFgHg");
	this.shape_66.setTransform(88.3,-87.9);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgkDpQAWgTAJgZQAJgagBgnIAAiUIAAgYQABgKgDgFQgCgFgHgCIgWgEIAAgLQApgMARgbIAIAAIAAD0QAAAigRAgQgSAgghAVgAgGjFQgGgIABgKQgBgJAHgHQAFgIAMABQAXAAAAAYQAAALgIAHQgGAGgMAAIgCAAQgIAAgFgHg");
	this.shape_67.setTransform(100.4,-87.9);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgJAJQgKAJgNAEQgNAGgQAAQgYgBgRgHQgRgJgMgOQgMgNgFgUQgGgSABgXQAAgcAKgXQAKgXAQgPQAQgPAVgHQAUgJAWABIASACIARAFIAQAGIAfgPIAEACIABBXIAABWQAAAWATAAIAIgCIAGgDIAFgEIAFADIgKARIgMAMQgIAFgMABQgRAAgIgMgAgphaQgNAGgLALQgMAKgHASQgHARAAAZQAAARAFASQAFAQAJANQAJAOAOAHQANAIASAAQAOAAALgHQAMgHAKgNQAJgMAFgRQAFgSABgSIAAgHQAAgogPgXQgOgWgjAAQgNAAgNAEg");
	this.shape_68.setTransform(152.5,-88.5);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AgQCJQgJgEgEgIQgGgIgBgOIgCgiIAAh+IgPAAIgPABQgIAAAAgEQAAgFAHgDQAZgKAKgNIAMgTIAMgdIAHAAIAAAeIABAfIBLgCIAAAUIhLACIAAByQgBAhAEARQAFARAWgBQAQgBAcgPIAFAIQgMAOgPAFQgPAHgcgBQgNAAgKgCg");
	this.shape_69.setTransform(103,-90.8);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("ABhBrIgfgBIgdABIgYABIAAgIIAUgFQAOgEAAgGQAAgGgJgKIgEgGIgDgEIglgvIgpA5QgGAHAAAGQAAALAWADIAQAEIAAAIIgxgCIg2ACIAAgIIAPgEQAQgDAKgJQALgJAMgRIApg3Ig4hDQgYgdgJgBIgRgFIAAgJIA1ACIA5gCIAAAKIgUAEQgJABAAAHQAAAHANAPIAfApIAfgqQAHgJABgIQgBgMgQgCIgQgDIAAgJIAaACIAfAAQAhAAAKgCIAAAJIgSAEQgNACgKAIQgKAGgNARIgjAwIBEBVQAPAUAJADIAPAGIAAAIg");
	this.shape_70.setTransform(124.2,-88.4);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AgnBrQgTgJgMgPQgNgQgHgVQgIgVAAgYQABgYAHgVQAJgWAPgPQAOgQATgJQAUgJAWAAQATAAAPAFQAPAGALALQAMALAGAQQAHAPABATIicAAIgCAWQAAAVAHASQAGASAMANQALANAQAHQAQAHAUAAQAUAAAQgHQAQgIAUgSIABANQgoAxg8AAQgUAAgRgJgAgjhXQgRAQgGAbIBUAAQASAAAJgDQAIgCgEgPQgEgPgLgMQgLgLgWAAQgaAAgSAPg");
	this.shape_71.setTransform(99.3,-88.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("ABgBrIgdgBIgeABIgXABIAAgIIATgFQAOgEAAgGQAAgGgIgKIgFgGIgDgEIgkgvIgqA5QgGAHAAAGQAAALAWADIARAEIAAAIIgygCIg2ACIAAgIIAQgEQAOgDALgJQALgJAMgRIApg3Ig3hDQgZgdgJgBIgSgFIAAgJIA2ACIA4gCIAAAKIgUAEQgJABABAHQgBAHANAPIAgApIAfgqQAIgJgBgIQAAgMgPgCIgRgDIAAgJIAbACIAeAAQAgAAAMgCIAAAJIgTAEQgNACgKAIQgKAGgMARIgkAwIBDBVQAQAUAJADIAQAGIAAAIg");
	this.shape_72.setTransform(154.7,-88.4);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AgVC4IgQAAIg9ACIAAgIIARgFIAOgDIAGgHIADgJIABgQIAAiKIgqgCIAAgJIAUgJIANgIIAGgGIABgIQAAgOAEgWQAFgWALgWQALgXASgRQATgSAcgDIAIgBIAIgBQAuAAAAAYQABAIgGAGQgGAFgKAAIgJgDIgQgGIgQgFIgQgDQgSAAgJAIQgKAIgEANQgDAMgBARIgBAgIAAAaIABAOIBIABIAAAUIhHACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_73.setTransform(104.7,-96.2);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("Ag3CYQgSgEgKgIQgJgGgCgIIgDgNQAAgKAFgDQAFgGAJAAQANABADAHIAHAQQAFAIAKAIQAJAHAbAAQAkAAATgUQATgTAAgmIAAhDIgLAZQgHANgLAJQgKALgOAFQgNAHgQAAQgTgBgRgHQgRgHgMgNQgNgOgGgSQgIgSABgVQAAgaAIgVQAJgVAPgRQAPgPAUgJQAUgIAVAAIAbACIAUAFIAQAGIAfgUIAFABIAADUQAAAVgIASQgIATgPANQgOANgVAIQgUAIgYAAQgfAAgSgFgAgaiBQgMAHgJAKQgJAMgHARQgFARAAAWQAAARADAQQAEAQAHANQAJAMAMAJQALAHATAAQAPAAANgIQANgIALgOQAKgNAFgQQAFgQABgRIAAgFQAAgSgDgPQgEgOgHgMQgJgMgNgGQgNgHgVAAQgNABgNAFg");
	this.shape_74.setTransform(152.5,-84.6);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgEByIhVi+IgKgSQgEgDgIgCIgYgFIAAgJIA/ABIBBgBIAAAJIgjAFQgLACAAAHQABAHAJAYIA1B8IA0h+QAFgNABgJQAAgPgYgDIgVgDIAAgJIA2ABIA6gBIAAAJIgeAEQgKACgEAEIgKATIhOC9g");
	this.shape_75.setTransform(126.7,-87.7);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AhEBmIgFhAIAJAAQAEAQAHAMQAHAMAKAIQAIAJAKAEQALAFAJAAQAUAAAMgLQANgLAAgSQAAgggzgTQgmgNgPgQQgRgPABgZQAAgbAVgQQAWgQAfAAQAjAAAXANIADAxIgLAAQgCgJgGgJIgOgQIgQgLQgJgEgFAAQgpAAAAAlQAAAPAOAKQANALAaAKQA/AYAAArQAAAQgFANQgHAMgKAJQgLAJgOAEQgPAFgOAAQgoAAgagOg");
	this.shape_76.setTransform(103.7,-88.5);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AAcB2IgngBIgHAAIglABIgfABIAAgIIAcgGQALgCADgGQAEgGAAgOIAAhrQAAgLgGgFQgEgFgQgDIgQgEIABgIQAXgIAOgKQAOgLAMgXIAKAAIACAhIAAAlQAKgUAUgSQATgTAPAAQAOAAAHAIQAIAHAAAMQAAAKgGAGQgGAFgJAAQgJAAgKgEQgKgFgIAAQgGAAgHAGIgLAPIgIARIgDAOIAABcQAAAPAEAEQAEAFAQACIArAHIAAAIg");
	this.shape_77.setTransform(155.6,-89.5);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AgVC4IgQAAIg9ACIAAgIIARgFIAOgDIAHgHIACgJIAAgQIAAiKIgpgCIAAgJIAVgJIAMgIIAGgGIABgIQAAgOAEgWQAFgWALgWQALgXASgRQATgSAcgDIAIgBIAIgBQAuAAABAYQAAAIgGAGQgGAFgKAAIgKgDIgPgGIgQgFIgQgDQgSAAgJAIQgJAIgFANQgEAMAAARIAAAgIAAAaIAAAOIBIABIAAAUIhHACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_78.setTransform(159.3,-96.2);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("ABhBrIgfgBIgdABIgYABIAAgIIAUgFQAOgEAAgGQAAgGgJgKIgEgGIgDgEIglgvIgpA5QgGAHAAAGQAAALAWADIAQAEIAAAIIgxgCIg2ACIAAgIIAPgEQAPgDALgJQAKgJANgRIApg3Ig4hDQgYgdgJgBIgSgFIAAgJIA2ACIA5gCIAAAKIgVAEQgIABgBAHQAAAHAOAPIAfApIAfgqQAIgJAAgIQgBgMgPgCIgRgDIAAgJIAaACIAeAAQAiAAAKgCIAAAJIgSAEQgNACgKAIQgLAGgMARIgjAwIBEBVQAPAUAJADIAPAGIAAAIg");
	this.shape_79.setTransform(134,-88.4);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgVC4IgQAAIg9ACIAAgIIARgFIANgDIAHgHIADgJIABgQIAAiKIgpgCIAAgJIATgJIANgIIAGgGIABgIQAAgOAFgWQAEgWALgWQALgXATgRQARgSAdgDIAIgBIAIgBQAvAAgBAYQAAAIgFAGQgGAFgJAAIgKgDIgQgGIgQgFIgRgDQgRAAgJAIQgKAIgDANQgFAMAAARIgBAgIAAAaIABAOIBHABIAAAUIhGACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_80.setTransform(132.4,-96.2);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AhMBaQgSgUAAgjIAAh0QAAgKgGgEQgHgEgXgDIAAgIIBHAAIAACPQAAAbAKAMQAJAKAaAAQAlAAAggcIAAiGIgCgJIgIgFIgPgEIgbgDIAAgJIBYAAIAACjIABAQQABAGAFADIALADIAVABIABAEIAAAEIhMAVIAAgrQgaAVgUALQgSALgUAAQgdAAgSgVg");
	this.shape_81.setTransform(105.3,-87.9);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AhEBmIgFhAIAJAAQAEAQAHAMQAIAMAJAIQAIAJALAEQAKAFAJAAQAUAAANgLQAMgLAAgSQAAggg0gTQglgNgQgQQgPgPAAgZQgBgbAWgQQAWgQAgAAQAiAAAWANIAEAxIgLAAQgCgJgGgJIgOgQIgQgLQgIgEgGAAQgpAAAAAlQAAAPAOAKQANALAaAKQBAAYgBArQABAQgHANQgGAMgKAJQgLAJgOAEQgPAFgOAAQgoAAgagOg");
	this.shape_82.setTransform(156.9,-88.5);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AA3BmQgHgMAAgVIAAgRIgLAXQgGALgJAJQgKAJgNAEQgNAGgQAAQgYgBgRgHQgSgJgLgOQgMgNgFgUQgGgSABgXQAAgcAKgXQAJgXARgPQAQgPAVgHQAUgJAWABIASACIARAFIAQAGIAfgPIAEACIABBXIAABWQAAAWATAAIAIgCIAGgDIAFgEIAFADIgKARIgNAMQgHAFgMABQgSAAgIgMgAgphaQgNAGgLALQgLAKgIASQgHARAAAZQAAARAFASQAEAQAKANQAJAOAOAHQANAIASAAQAOAAALgHQANgHAIgNQAKgMAFgRQAGgSAAgSIAAgHQAAgogPgXQgPgWgiAAQgNAAgNAEg");
	this.shape_83.setTransform(122.7,-88.5);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("Ag3CYQgSgEgKgIQgJgGgCgIIgDgNQAAgKAFgDQAFgGAJAAQANABADAHIAHAQQAFAIAKAIQAJAHAbAAQAkAAATgUQATgTAAgmIAAhDIgLAZQgHANgLAJQgKALgOAFQgNAHgQAAQgTgBgRgHQgRgHgMgNQgNgOgGgSQgIgSABgVQAAgaAIgVQAJgVAPgRQAPgPAUgJQAUgIAVAAIAcACIATAFIAQAGIAfgUIAFABIAADUQAAAVgIASQgIATgPANQgOANgVAIQgUAIgYAAQgfAAgSgFgAgaiBQgMAHgJAKQgJAMgHARQgFARAAAWQAAARADAQQAEAQAHANQAJAMAMAJQALAHATAAQAPAAANgIQANgIALgOQAKgNAFgQQAFgQABgRIAAgFQAAgSgDgPQgEgOgHgMQgJgMgNgGQgNgHgVAAQgNABgNAFg");
	this.shape_84.setTransform(158.8,-84.6);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AASB2IAAgJIAfgFQAMgBAAgVIAAheQAAgfgKgSQgLgUgfAAQgiAAgiAiIAACIQAAAIANAEIAhAIIAAAJIgSgBIgYgBIgSAAIg9ACIAAgJIAegGQALgCAAgPIAAhuQAAgRgHgGQgIgGgRgDIAAgLQAjgHAWgqIAJAAIAAAxQAUgRAbgMQAZgLATABQBAAAAABMIAABvQABAKACAFQADAHAIABIAZAFIAAAJQg7gEg6AEg");
	this.shape_85.setTransform(131.2,-89.3);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AA7ByIgvhyIg6ByIgLAAIhkjHQgHgPgNgCIgOgCIAAgJIA0ACIA5gCIAAAJQgWAEgHAEQgGAFAFAMIBJCYIAshaIgVg6QgGgPgEgFQgFgEgEAAIgXgFIAAgJIA8ACIA8gCIAAAJIgcAFIgMAFIgFAGIAAAGIAEAHIA3CPIA4iFIAFgLIgDgLIgHgJQgEgDgHgBIgWgEIAAgJIAuACQAjAAARgCIAAAJIgPADQgRAFgLAaIhRC4g");
	this.shape_86.setTransform(153.9,-87.9);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AAcB2IgngBIgHAAIglABIgfABIAAgIIAcgGQAMgCACgGQADgGABgOIAAhrQgBgLgFgFQgEgFgQgDIgPgEIAAgIQAXgIAOgKQAPgLALgXIAKAAIABAhIABAlQALgUATgSQAUgTAOAAQAOAAAHAIQAIAHAAAMQAAAKgGAGQgGAFgJAAQgJAAgLgEQgJgFgIAAQgGAAgHAGIgLAPIgHARIgEAOIAABcQAAAPAFAEQAEAFAPACIArAHIAAAIg");
	this.shape_87.setTransform(96.9,-89.5);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AAcB2IgngBIgHAAIgkABIggABIAAgIIAcgGQAMgCADgGQACgGAAgOIAAhrQAAgLgEgFQgFgFgRgDIgOgEIABgIQAVgIAPgKQAOgLAMgXIAKAAIACAhIAAAlQAKgUAUgSQATgTAPAAQAOAAAIAIQAHAHAAAMQAAAKgGAGQgGAFgJAAQgJAAgKgEQgLgFgHAAQgGAAgGAGIgMAPIgIARIgDAOIAABcQAAAPAEAEQAFAFAPACIAsAHIAAAIg");
	this.shape_88.setTransform(151.4,-89.5);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FFFFFF").s().p("ABoC5IgXgBIgXABIgfABIAAgIIAXgHIAKgFQADgDAAgJIAAh0QAAgYgOgOQgNgNgXAAQgVAAgPALQgRAKgTAYIAAB6IACAJIAJAFIAmAKIAAAIIgYgBIglgBIgnABIgYABIAAgIIAegHIAKgDQACgDAAgGIAAkcIgCgMIgFgIIgNgIIgVgEIAAgHQAXgCAngTIAMAAIAADFQAqgzAvABIAJAAIAJABQAXAHANATQAMARAAAeIAAB6IADAJQACACAJACIAZAHIAAAIg");
	this.shape_89.setTransform(97.8,-96.1);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AgVC4IgQAAIg9ACIAAgIIARgFIANgDIAHgHIADgJIABgQIAAiKIgqgCIAAgJIAUgJIANgIIAGgGIABgIQAAgOAFgWQAEgWALgWQALgXATgRQARgSAdgDIAIgBIAIgBQAvAAgBAYQAAAIgFAGQgGAFgJAAIgKgDIgQgGIgQgFIgRgDQgRAAgJAIQgKAIgDANQgFAMAAARIgBAgIAAAaIABAOIBHABIAAAUIhGACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_90.setTransform(172.9,-96.2);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FFFFFF").s().p("AA7ByIgwhyIg5ByIgMAAIhjjHQgHgPgNgCIgNgCIAAgJIAzACIA6gCIAAAJQgYAEgGAEQgGAFAFAMIBJCYIAshaIgVg6QgGgPgEgFQgEgEgFAAIgYgFIAAgJIA9ACIA8gCIAAAJIgbAFIgNAFIgEAGIAAAGIACAHIA3CPIA6iFIAEgLIgDgLIgHgJQgFgDgFgBIgYgEIAAgJIAvACQAjAAAQgCIAAAJIgNADQgSAFgLAaIhRC4g");
	this.shape_91.setTransform(97.5,-87.9);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AgWC4IgPAAIg9ACIAAgIIASgFIAMgDIAIgHIACgJIAAgQIAAiKIgogCIAAgJIAUgJIAMgIIAGgGIABgIQAAgOAFgWQAEgWALgWQALgXATgRQARgSAdgDIAIgBIAIgBQAvAAAAAYQgBAIgFAGQgGAFgKAAIgKgDIgOgGIgRgFIgRgDQgRAAgJAIQgJAIgFANQgEAMAAARIAAAgIAAAaIAAAOIBIABIAAAUIhHACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_92.setTransform(105.5,-96.2);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFFFFF").s().p("AgWC4IgPAAIg9ACIAAgIIASgFIAMgDIAIgHIACgJIAAgQIAAiKIgogCIAAgJIAUgJIAMgIIAGgGIABgIQAAgOAFgWQAEgWALgWQALgXATgRQARgSAdgDIAIgBIAIgBQAvAAAAAYQgBAIgFAGQgGAFgKAAIgKgDIgOgGIgRgFIgQgDQgSAAgJAIQgJAIgFANQgEAMAAARIAAAgIAAAaIAAAOIBIABIAAAUIhHACIAACMQAAAiAXADIAlAGIAAAJg");
	this.shape_93.setTransform(166.3,-96.2);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AgoBrQgSgJgMgPQgNgQgHgVQgHgVAAgYQgBgYAJgVQAHgWAPgPQAPgQATgJQAUgJAWAAQASAAAQAFQAOAGAMALQAMALAGAQQAHAPAAATIibAAIgBAWQgBAVAHASQAGASAMANQALANARAHQAPAHAVAAQASAAARgHQAQgIAUgSIACANQgoAxg9AAQgUAAgSgJgAgjhXQgRAQgGAbIBVAAQARAAAJgDQAIgCgEgPQgFgPgKgMQgLgLgWAAQgaAAgSAPg");
	this.shape_94.setTransform(97.6,-88.5);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("ABkC5IgigBIgjABIgaABIAAgIIAagDQAMgBAAgEIgDgIIgIgLIgPgSIgTgaIgQgTIgJgLIgHgGIgEgBIgDAAIgFAAIgKAAIAABQQABAOACAEQADAEAJABIAVAFIAAAIIgWgBIgfgBIgeABIgXABIAAgIIAVgEQALgCACgDQADgFAAgOIAAkVIgCgLIgEgGIgLgEIgSgEIAAgIQAdgFAegUIAJAAIAAD2QAMABALgIIAegVIAZgYQAIgHAAgEQAAgMgjgFIAAgJIBwAAIAAAJQgnAEgeAYIgwArIAZAhIAfAnIAfAhQAOAOALABIAGACIAGABIAMADIAAAIg");
	this.shape_95.setTransform(159.6,-96.1);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AA4BmQgIgMAAgVIAAgRIgKAXQgHALgKAJQgJAJgMAEQgOAGgRAAQgWgBgSgHQgRgJgMgOQgLgNgGgUQgFgSAAgXQgBgcAKgXQAKgXARgPQAQgPAUgHQAWgJAVABIASACIARAFIAQAGIAegPIAGACIAABXIAABWQAAAWAUAAIAHgCIAFgDIAGgEIAFADIgKARIgMAMQgJAFgLABQgSAAgHgMgAgphaQgNAGgMALQgKAKgIASQgHARAAAZQAAARAFASQAEAQAKANQAKAOANAHQAOAIARAAQAOAAAMgHQALgHAKgNQAJgMAFgRQAFgSAAgSIAAgHQAAgogOgXQgOgWgjAAQgMAAgOAEg");
	this.shape_96.setTransform(102.4,-88.5);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#FFFFFF").s().p("AhOCcQgGgHABgHQAAgHADgFQAGgFAJAAIALABIAKACIAHABIAFgDIAEgCIACgDIAFgIIAFgPQAIgVAAgGQAAgJgFgOIhFi0QgEgNgLgCIgUgHIAAgIIA+ACIAzgCIAAAIIgPADIgPACIgLAGQgDAEACAHIA4CfIA0iPIACgSQAAgJgKgDIgegIIAAgIIAuACIAwgCIAAAIIgSAGQgHACgFAHQgHAHgHAVIhTDdQgKAbgOANQgOANgPAAQgLAAgFgHg");
	this.shape_97.setTransform(194.1,-83);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#FFFFFF").s().p("AgQCJQgIgEgFgIQgGgIgBgOIgCgiIAAh+IgPAAIgPABQgIAAAAgEQAAgFAHgDQAZgKAKgNIAMgTIAMgdIAHAAIAAAeIABAfIBKgCIAAAUIhKACIAAByQgBAhAEARQAFARAWgBQARgBAbgPIAFAIQgMAOgPAFQgQAHgbgBQgNAAgKgCg");
	this.shape_98.setTransform(173.9,-90.8);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#FFFFFF").s().p("AgGCvIijACIAAgKIAogDQAJAAAEgDQADgEABgMIAAkZQAAgNgDgGQgEgGgIgBIgogDIAAgLICXACICVgCIgCAnIABAnIgHAAIgPgkIgKgTQgFgGgEgCIgMgCIiBAAQgKAAgDAFQgDAGgBANIAACBIB9AAQAKAAAFgDQAEgDACgLIAHgnIALAAQgCBCACBDIgGAAIgMgsIgHgNQgEgEgHgCIgPgCIgXgBIhaAAIAACMQABAMAEAFQAEAFAPAAIB7AAIAXgDQAJgCAJgJQAJgIAJgPIAUgqIALAAQgMAygBArg");
	this.shape_99.setTransform(72.5,-95.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5,p:{x:71.3}},{t:this.shape_4,p:{x:101.4}},{t:this.shape_3,p:{x:123.3}},{t:this.shape_2,p:{x:145.4}},{t:this.shape_1,p:{x:171.7}},{t:this.shape}]}).to({state:[{t:this.shape_5,p:{x:102.5}},{t:this.shape_7,p:{x:125.8}},{t:this.shape_3,p:{x:141}},{t:this.shape_6,p:{x:160.7}}]},1).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},1).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11,p:{x:162.7}}]},1).to({state:[{t:this.shape_16,p:{x:98.9}},{t:this.shape_3,p:{x:114.3}},{t:this.shape_15},{t:this.shape_14,p:{x:162.1}}]},1).to({state:[{t:this.shape_19,p:{x:103.4}},{t:this.shape_18,p:{x:131.4}},{t:this.shape_17,p:{x:158.7}}]},1).to({state:[{t:this.shape_21,p:{x:96.9}},{t:this.shape_3,p:{x:118.2}},{t:this.shape_20},{t:this.shape_14,p:{x:166.1}}]},1).to({state:[{t:this.shape_23},{t:this.shape_22}]},1).to({state:[{t:this.shape_25,p:{x:104.5}},{t:this.shape_24},{t:this.shape_14,p:{x:158.5}}]},1).to({state:[{t:this.shape_4,p:{x:103.2}},{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_29,p:{x:89.7}},{t:this.shape_18,p:{x:125.9}},{t:this.shape_1,p:{x:153.2}},{t:this.shape_28,p:{x:178}}]},1).to({state:[{t:this.shape_21,p:{x:109.5}},{t:this.shape_30},{t:this.shape_7,p:{x:157}}]},1).to({state:[{t:this.shape_29,p:{x:102.3}},{t:this.shape_4,p:{x:138.6}},{t:this.shape_31}]},1).to({state:[{t:this.shape_33},{t:this.shape_32,p:{x:134.1}},{t:this.shape_16,p:{x:156.5}}]},1).to({state:[{t:this.shape_35},{t:this.shape_29,p:{x:135.3}},{t:this.shape_34}]},1).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36,p:{x:151.3}},{t:this.shape_7,p:{x:171.9}}]},1).to({state:[{t:this.shape_40},{t:this.shape_39,p:{x:127.6}},{t:this.shape_18,p:{x:155.7}}]},1).to({state:[{t:this.shape_41},{t:this.shape_19,p:{x:140.3}}]},1).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_29,p:{x:154}}]},1).to({state:[{t:this.shape_29,p:{x:103.5}},{t:this.shape_44},{t:this.shape_11,p:{x:164.9}}]},1).to({state:[{t:this.shape_46},{t:this.shape_3,p:{x:126.8}},{t:this.shape_45}]},1).to({state:[{t:this.shape_48,p:{x:105.9}},{t:this.shape_47},{t:this.shape_36,p:{x:153.1}}]},1).to({state:[{t:this.shape_51},{t:this.shape_29,p:{x:112.1}},{t:this.shape_50},{t:this.shape_49,p:{x:174.6}}]},1).to({state:[{t:this.shape_52},{t:this.shape_17,p:{x:111.9}},{t:this.shape_49,p:{x:138.1}},{t:this.shape_29,p:{x:175.1}}]},1).to({state:[{t:this.shape_53},{t:this.shape_2,p:{x:144.6}}]},1).to({state:[{t:this.shape_54},{t:this.shape_11,p:{x:129.8}},{t:this.shape_2,p:{x:157.4}}]},1).to({state:[{t:this.shape_29,p:{x:101.9}},{t:this.shape_18,p:{x:138.2}},{t:this.shape_55}]},1).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_18,p:{x:174.6}}]},1).to({state:[{t:this.shape_59},{t:this.shape_29,p:{x:129.6}},{t:this.shape_18,p:{x:165.9}}]},1).to({state:[{t:this.shape_18,p:{x:105}},{t:this.shape_14,p:{x:132.1}},{t:this.shape_60}]},1).to({state:[{t:this.shape_61},{t:this.shape_7,p:{x:128.5}},{t:this.shape_48,p:{x:148.7}}]},1).to({state:[{t:this.shape_63},{t:this.shape_7,p:{x:132.9}},{t:this.shape_62}]},1).to({state:[{t:this.shape_66},{t:this.shape_18,p:{x:110.1}},{t:this.shape_65},{t:this.shape_64}]},1).to({state:[{t:this.shape_67},{t:this.shape_18,p:{x:122.2}},{t:this.shape_39,p:{x:150.1}}]},1).to({state:[{t:this.shape_69},{t:this.shape_28,p:{x:124}},{t:this.shape_68}]},1).to({state:[{t:this.shape_71},{t:this.shape_70},{t:this.shape_7,p:{x:144.5}},{t:this.shape_16,p:{x:164.6}}]},1).to({state:[{t:this.shape_73},{t:this.shape_18,p:{x:126.7}},{t:this.shape_72}]},1).to({state:[{t:this.shape_76},{t:this.shape_75},{t:this.shape_74}]},1).to({state:[{t:this.shape_18,p:{x:104.7}},{t:this.shape_32,p:{x:130.5}},{t:this.shape_2,p:{x:154.9}}]},1).to({state:[{t:this.shape_14,p:{x:105.7}},{t:this.shape_2,p:{x:131.4}},{t:this.shape_77}]},1).to({state:[{t:this.shape_18,p:{x:104.7}},{t:this.shape_32,p:{x:130.5}},{t:this.shape_2,p:{x:154.9}}]},1).to({state:[{t:this.shape_14,p:{x:105.7}},{t:this.shape_2,p:{x:131.4}},{t:this.shape_77}]},1).to({state:[{t:this.shape_2,p:{x:107}},{t:this.shape_79},{t:this.shape_78}]},1).to({state:[{t:this.shape_81},{t:this.shape_80},{t:this.shape_4,p:{x:154.4}}]},1).to({state:[{t:this.shape_6,p:{x:104.9}},{t:this.shape_18,p:{x:131.2}},{t:this.shape_82}]},1).to({state:[{t:this.shape_83},{t:this.shape_7,p:{x:143.9}}]},1).to({state:[{t:this.shape_18,p:{x:101.1}},{t:this.shape_85},{t:this.shape_84}]},1).to({state:[{t:this.shape_87},{t:this.shape_25,p:{x:121.6}},{t:this.shape_86}]},1).to({state:[{t:this.shape_18,p:{x:101.1}},{t:this.shape_85},{t:this.shape_84}]},1).to({state:[{t:this.shape_89},{t:this.shape_2,p:{x:127.2}},{t:this.shape_88},{t:this.shape_7,p:{x:169.1}}]},1).to({state:[{t:this.shape_91},{t:this.shape_29,p:{x:138.3}},{t:this.shape_90}]},1).to({state:[{t:this.shape_92},{t:this.shape_3,p:{x:120.9}},{t:this.shape_7,p:{x:136}},{t:this.shape_14,p:{x:155.5}}]},1).to({state:[{t:this.shape_94},{t:this.shape_29,p:{x:131.7}},{t:this.shape_93}]},1).to({state:[{t:this.shape_7,p:{x:103.9}},{t:this.shape_14,p:{x:123.4}},{t:this.shape_4,p:{x:148.8}}]},1).to({state:[{t:this.shape_96},{t:this.shape_18,p:{x:130.3}},{t:this.shape_95}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_99},{t:this.shape_29,p:{x:112.8}},{t:this.shape_18,p:{x:149}},{t:this.shape_98},{t:this.shape_97}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-86,-7.7,436,337.8);
// library properties:
lib.properties = {
	id: '1AC52D93D16545FD9C919F2EFDC647AE',
	width: 256,
	height: 256,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Bitmap1.jpg?1547720891816", id:"Bitmap1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['1AC52D93D16545FD9C919F2EFDC647AE'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;